rcrestore: enforce sudo, fix 'bad system call' bug
- Better error checking
- Code quality

diff --git a/bin/rcrestore b/bin/rcrestore
--- a/bin/rcrestore
+++ b/bin/rcrestore
@@ -1,15 +1,21 @@
 #! /bin/bash
 
-if [[ ! -f $1 ]]
+if [[ ${EUID} != 0 ]]
 then
-    echo "Usage: snap run rocketchat-server.rcrestore $SNAP_USER_COMMON/backup_file.tgz"
+    echo "[-] This task must be run with 'sudo'."
+    exit
+fi
+
+if [[ ! -f ${1} ]]
+then
+    echo "[-] Usage: snap run rocketchat-server.rcrestore ${SNAP_COMMON}/backup_file.tgz"
     exit
 fi
 
 cd ${1%/*}
-if [[ -z $(pwd | grep "$SNAP_USER_COMMON") ]]
+if [[ -z $(pwd | grep "${SNAP_COMMON}") ]]
 then
-    echo "Error: backup file must be within $SNAP_USER_COMMON."
+    echo "[-] Backup file must be within ${SNAP_COMMON}."
     exit
 fi
 
@@ -26,33 +32,36 @@ function ask_backup {
     exit
 }
 
-function error_check {
-    if [[ -n $(cat "$restore_dir/$1" | egrep "([Ee]rror|[Cc]annot|[Aa]bort|[Dd]enied)") ]]
-    then
-        echo "Restore aborted!"
-        echo "Check $restore_dir/$1 for details."
+function abort {
+        echo "[!] ${1}"
+        echo "[*] Check ${restore_dir}/${log_name} for details."
+        echo "[-] Restore aborted!"
         exit
-    fi
 }
 
 mongo parties --eval "db.getCollectionNames()" | grep "\[ \]" >> /dev/null || ask_backup
 
-echo "Extracting backup file..."
-restore_dir="$SNAP_USER_COMMON/restores"
-mkdir -p $restore_dir && cd $restore_dir
+echo "[*] Extracting backup file..."
+restore_dir="${SNAP_COMMON}/restore"
 log_name="extraction.log"
-tar zxvf $1 &> "$restore_dir/$log_name"
-error_check $log_name
+mkdir -p ${restore_dir}
+cd ${restore_dir}
+tar --no-same-owner --overwrite -zxvf ${1} &> "${restore_dir}/${log_name}"
+if [[ $? != 0 ]]
+then
+    abort "Failed to extract backup files to ${restore_dir}!"
+    exit
+fi
 
-echo "Cleaning database..."
-log_name="db_drop.log"
-mongo parties --eval "db.dropDatabase()" &> "$restore_dir/$log_name"
-error_check $log_name
-
-echo "Restoring data..."
-data_dir=$(ls -R $restore_dir | grep parties:)
+echo "[*] Restoring data..."
+data_dir=$(ls -R ${restore_dir} | grep parties:)
+data_dir=${data_dir/://}
 log_name="mongorestore.log"
-mongorestore --db parties ${data_dir/://} &> "$restore_dir/$log_name"
-error_check $log_name
+mongorestore --db parties --drop ${data_dir} &> "${restore_dir}/${log_name}"
+if [[ $? != 0 ]]
+then
+    abort "Failed to restore ${data_dir} using mongorestore!"
+    exit
+fi
 
-echo "Restore completed! Please restart the snap.rocketchat services to verify."
+echo "[+] Restore completed! Please restart the snap.rocketchat services to verify."
